### ISSUE TITLE
VCD UI plugin Version Compatibility matrix

### ISSUE THREAD

**Issue by swathishetty** [vmware/cloud-director-extension-standard-library#23]
Can we use angular 14 to build the UI plugin for VCD 10.2.x ?  Is there any limitation on this?  If yes, can i please get the version compatibility matrix  (supported versions of RxJS, Angular, and Clarity to be used )

**Comment by nvladimirovi** [comment]
Angular 9 is supported in 10.2 releases and every release after
Angular 15 is supported from 10.5 along with Angular 9

**Comment by josajunior81** [comment]
Do i need to use angluar to build the UI? Can I use any other UI framework? Do I have to init and build the project with the vcd-ext tool?

**Comment by nvladimirovi** [comment]
Hi @josajunior81,
> Do i need to use angluar to build the UI?

Yes, you need to use Angular

>Can I use any other UI framework?

Only if you host it in iframe, where you still need Angular to "encapsulate" the iframe so it can be rendered in Cloud Director.
Something like:
```html
<vcd-ui>
    <angular-plugin>
        <iframe>
            <react-app>
                Your Code...
            </react-app>
        </iframe>
    </angular-plugn>
</vcd-u>
```

>Do I have to init and build the project with the vcd-ext tool?

No, you need to use `vcd-ext-shell` now. Please visit https://blogs.vmware.com/cloudprovider/2023/04/developing-extensions-for-vmware-cloud-director-service.html and the linked inside links.

**Comment by josajunior81** [comment]
> Hi @josajunior81,
> 
> > Do i need to use angluar to build the UI?
> 
> Yes, you need to use Angular
> 
> > Can I use any other UI framework?
> 
> Only if you host it in iframe, where you still need Angular to "encapsulate" the iframe so it can be rendered in Cloud Director. Something like:
> 
> ```
> <vcd-ui>
>     <angular-plugin>
>         <iframe>
>             <react-app>
>                 Your Code...
>             </react-app>
>         </iframe>
>     </angular-plugn>
> </vcd-u>
> ```
> 
> > Do I have to init and build the project with the vcd-ext tool?
> 
> No, you need to use `vcd-ext-shell` now. Please visit https://blogs.vmware.com/cloudprovider/2023/04/developing-extensions-for-vmware-cloud-director-service.html and the links inside.
> 
> Please see #21 if you want to use Angular 15.

Thanks!

**Comment by swathishetty** [comment]
@nvladimirovi I am trying to load some icons from our internal library which is also built on top of clarity in the plugin code. I see these errors, this is not allowing us to override the icons. Any specific configurations to be made in angular.json ? Is there any known approach to override the central registry ? 
![image](https://github.com/vmware/cloud-director-extension-standard-library/assets/1817776/1d7da3ac-8d24-4a91-8e7c-fb9a84733e27)

**Comment by nvladimirovi** [comment]
@swathishetty The error means that you can not have webcomponents with the same tag name, do you try to register webcomponents?

**Comment by swathishetty** [comment]
@nvladimirovi in this case basically we are trying to use a module from our internal framework, which is trying to add the icons to clarity icons -  ClarityIcons.add(AllShapes); These are all custom shapes.  How can this be taken care ?

**Comment by nvladimirovi** [comment]
Importing only the ClarityModule should be enough.

This will give you the ability to use <clr-icon shape="X"> and under the hood <cds-icon shape="X"> will be used, but you don't need to worry about that.

The code that you are trying to run is to register Webcomponents, they are already registered.

**Comment by swathishetty** [comment]
@nvladimirovi  I am trying to use our internal library, which has these icons registered. In order to use that, I will have to import that module in my code. This is causing that error.

**Comment by nvladimirovi** [comment]
This won't be possible then, you need to change your lib to call `ClarityIcons.add(AllShapes)` conditionality.

**Comment by swathishetty** [comment]
can i override the one which was registered before ? In the sample template code can you please point me where clarity icons are registered. Can i remove that and proceed with the internal lib ?

**Comment by nvladimirovi** [comment]
The icons (webcomponents) are registered in the product itself, not in the plugins, and you can't override them.

**Comment by swathishetty** [comment]
@nvladimirovi Thank you. I am able find the root cause for the above issue. I see another issue on importing one of our internal module, the build is successful, but on importing the plugin and reloading the vcd, the below console error is coming up which is blocking the plugin binding.
![image](https://github.com/vmware/cloud-director-extension-standard-library/assets/1817776/0e750b6d-3714-4299-9ff7-ab62ecb244ee)

**Comment by swathishetty** [comment]
@nvladimirovi  we are trying to use our internal framework which basically adds some customization  to the clarity components. On loading the plugin the components are loading, but i see the clarity components coming up and not the internal ones. For eg: our internal library has done some customization on top of clarity wizard and I am trying to use the same in the code. But when i load the vcd plugin, the wizard is loading without any customization. Looks like its considering that  to be original clarity wizard and same is getting loaded. How does things work in this case ? Anything to be taken care here ?

**Comment by nvladimirovi** [comment]
As long as you use your own component selectors you should be fine in terms of JavaScript.

How do you extend the Clarity Components?
Do you inherit a Clarity class or do you add additional styles?

**Comment by swathishetty** [comment]
the selectors are from clarity, there are directives used to add additional styles/functionalities to it.

**Comment by nvladimirovi** [comment]
Have you tried to start the UI Emulator with source maps and try to debug the issue?
Can you place breakpoints in your Directives?
Do the Directives trigger at all?

Do you get any exceptions?

Did you solve the Exception from this https://github.com/vmware/cloud-director-extension-standard-library/issues/23#issuecomment-1698642652 or you still get it?

**Comment by swathishetty** [comment]
> Have you tried to start the UI Emulator with source maps and try to debug the issue? Can you place breakpoints in your Directives? Do the Directives trigger at all?
> 
> Do you get any exceptions?
> 
> Did you solve the Exception from this [#23 (comment)](https://github.com/vmware/cloud-director-extension-standard-library/issues/23#issuecomment-1698642652) or you still get it?

Working on these exceptions. Will get back on further assistance if needed. Thank you

**Comment by swathishetty** [comment]
> Angular 9 is supported in 10.2 releases and every release after Angular 15 is supported from 10.5 along with Angular 9

Does this mean angular 15.x , angular 14.x and below  are  supported in VCD 10.5 ?

**Comment by nvladimirovi** [comment]
We have tested only Angular 15 applications so far, but Angular 14 APIs are not fundamentally different I think, you can try to use it.

**Note**
When you compile your UI Plugin only the Angular APIs are present in the final bunde.js file,
the actual Angular Framework is in Cloud Director.

**Comment by swathishetty** [comment]
> We have tested only Angular 15 applications so far, but Angular 14 APIs are not fundamentally different I think, you can try to use it.
> 
> **Note** When you compile your UI Plugin only the Angular APIs are present in the final bundle.js file, the actual Angular Framework is in Cloud Director.

Tried with Angular 14.x. Getting the below build error.
![image](https://github.com/vmware/cloud-director-extension-standard-library/assets/1817776/3425b926-c07c-4043-b9f0-693777ac7e37)
package.json
{
  "name": "uiPlugin",
  "version": "0.0.2",
  "description": "",
  "scripts": {
    "clean": "rimraf dist",
    "build": "ng build"
  },
  "license": "BSD-2-Clause",
  "dependencies": {
    "@angular/animations": "^14.2.12",
    "@angular/common": "^14.2.12",
    "@angular/compiler": "^14.2.12",
    "@angular/core": "^14.2.12",
    "@angular/forms": "^14.2.12",
    "@angular/platform-browser": "^14.2.12",
    "@angular/platform-browser-dynamic": "^14.2.12",
    "@angular/router": "^14.2.12",
    "@cds/core": "6.3.1",
    "@clr/angular": "15.0.3",
    "@clr/ui": "15.0.3",
    "@ngrx/store": "^14.3.2",
    "@vcd/bindings": "9.1.1",
    "@vcd/i18n": "12.0.0",
    "@vcd/plugin-builders": "15.0.1",
    "@vcd/sdk": "15.0.2",
    "rxjs": "^7.8.1",
    "tslib": "^2.6.0",
    "zone.js": "^0.11.8"
  },
  "devDependencies": {
    "@angular/cli": "^14.2.10",
    "typescript": "4.8.4"
  }
}

**Comment by nvladimirovi** [comment]
Yes, unfortunately, you will need to upgrade to Angular 15.

**Comment by swathishetty** [comment]
Thank you @nvladimirovi for the clarification, that helps. We are also trying  to explore on how to embed the VCD UI plugin code inside an iframe. Also we are looking for details on how to call the  VCD native and extension API’s, plus manage session from the extension code when present inside an iframe. Is this doable ? or do we have any constraints ?

**Comment by nvladimirovi** [comment]
Yes, it is but we don't have a guide exactly. Even if you use an iframe, you would need a "native" Angular UI Plugin that will host the iframe inside.

**Comment by swathishetty** [comment]
so you mean the application has to be hosted somewhere in order to access it via iframe ? only then we will be able to use it inside plugin ? 
 <vcd--container>
    <angular-plugin>
        <iframe src="url">
     
        </iframe>
    </angular-plugin>
</vcd-u>

**Comment by nvladimirovi** [comment]
Yes, you need to host your Application somewhere.

When you want to use iframe typically your approach is this:
- Create a Simple Angular UI Plugin
- Add one component IframeWrapperComponent that hosts the iframe
- You can use that IframeWrapperComponent to pass data to the iframe via [messege](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) or query params in the iframe URL

Now in terms of hosting.
**Option 1 - No hosting server**
When you build the Application that is meant to be hosted somewhere and present in iframe you can put that Application (i.e build files) as assets to the Simple Angular Plugin, that way VCD will host your Application files.
When you do that you can embed your Application like this
`<iframe src="https://vcd.com/<PROVIDER OR TENANT>/uiPlugins/<PLUGIN_ID>/<RESOURCE_ID>/assets/<YOUR_APPLICATION_INDEX_HTML>"></iframe>`

**Option 2 - hosting server**
The other option is, you to deploy a Server that hosts your Application and embed the iframe in the Simple Angular UI Plugin

It's worth mentioning here that I'm brainstorming with you, maybe some impediments will come out for either Option 1 or 2.
The most important thing is iframe approach is possible and some of our Internal VMware Solutions, such as Cloud Director Availability, are using iframes.

**Comment by swathishetty** [comment]
Thank you for the details. Tried option 1 by moving the build files of the the application to the asset folder and tried loading the below url in an iframe. Ended up with the below error.

![image](https://github.com/vmware/cloud-director-extension-standard-library/assets/1817776/6a8e3599-848a-402f-958e-7aced36699a1)

**Comment by swathishetty** [comment]
@nvladimirovi  this is working for me now, i was passing the wrong plugin resourceId in the URL, hence it was not able to find the html. Thank you
