### ISSUE TITLE
Unable to run the emulator 

### ISSUE THREAD

**Issue by swathishetty** [vmware/cloud-director-extension-standard-library#28]
@nvladimirovi  while trying to run the emulator, I came across the below issue. Can you please let me know on how can we fix this ? Also is it possible to use ng serve to run the code locally without emulator ?
 
![image](https://github.com/vmware/cloud-director-extension-standard-library/assets/1817776/b01b0d14-eff8-4579-8e67-ef92fc768d28)

**Comment by nvladimirovi** [comment]
Hey, try using NodeJS v14.20.

**Comment by swathishetty** [comment]
installed node v14.20. Still see the same issue. I have updated the JWT and auth token in config.js inside .ui-emulator and tried running npm start. Anything else to be done ?
![image](https://github.com/vmware/cloud-director-extension-standard-library/assets/1817776/b859b41d-c5fc-4e09-b6c5-9ca3a6bf2f15)

**Comment by nvladimirovi** [comment]
Did you install your npm dependencies in the `ui` folder?

**Comment by swathishetty** [comment]
yes, i did install npm dependencies in both ui and .ui-emulator folder. Also i ran the build in ui folder and have the dist generated. After all these steps i tried running emulator and landed on this issue.

**Comment by nvladimirovi** [comment]
Can you please attach the config json.

**Comment by nvladimirovi** [comment]
You can check if the CWD of the child process is correct by going to `add-on/multi-instance-skeleton/.ui-emulator/node_modules/@vcd/ui-emulator/utils/lib/ui-emulator-utils.js`

Seach for `child_process = cp.spawn("npm", ["run", "build"], { cwd: pluginRootDir, stdio: "inherit" });`

You can add `console.log(pluginRootDir)` or run the script in debug mode with VSCode (JavaScript Debug Terminal)
![image](https://github.com/vmware/cloud-director-extension-standard-library/assets/29869465/e0777859-02ed-4430-850b-0f1081da6513)

See if the path is correct, if not maybe we have bug for windows and we'll fix it shortly.
Meanwhile, you can mutate the code in node_modules for now to unblock you.

**Comment by nvladimirovi** [comment]
@swathishetty did you manage to start the emulator, we are looking for a fix for your issue.

**Comment by nvladimirovi** [comment]
Fixed by https://github.com/vmware/cloud-director-extension-standard-library/pull/32

**Comment by nvladimirovi** [comment]
Upgrade [@vcd/](https://www.npmjs.com/package/@vcd/ui-emulator) to v15.0.3.
