### ISSUE TITLE
Facing issues in running the unit test cases 

### ISSUE THREAD

**Issue by swathishetty** [vmware/cloud-director-extension-standard-library#30]
@nvladimirovi we are trying to run the UT's and seems like the vcd sdk is throwing the errors due to which the tests are failing. Is there a way to avoid this issue ?
![image](https://github.com/vmware/cloud-director-extension-standard-library/assets/1817776/72ea07db-215c-4c55-aa91-a1094432b6b2)

**Comment by swathishetty** [comment]
Also how is the e2e test done ?  are there any specific frameworks recommended to do it ?

**Comment by nvladimirovi** [comment]
Hi @swathishetty 
### How to solve the problem in unit tests
to solve the above issue if you use Karma make sure you added systemJS as a library in the Karma's runtime environment.
Install SystemJS
```bash
npm i systemjs@0.20.19 -D -E
```
Add SystemJS in Karma runtime
```javascript
{ pattern: "../../../node_modules/systemjs/dist/system.js", included: true, watched: true },
```
You may also need to add this script in the browser runtime
```typescript
import System from "systemjs/dist/system";
// Provides the @vcd/common module so loading the VcdApiClient does not throw an error.
window.SystemJs = System.registry.set("@vcd/common", System.newModule({}));
```

Because SDK uses artifacts from `@vcd/common` and there is no VCD instance that can provide valid values, some of your unit tests may fail.
For example if you `@Inject(AuthTokenHolderService) token: AuthTokenHolderService` you may be able to inject something but there would be no value because nobody set it.

### What to use for e2e testing
We use [Cypress](https://www.cypress.io/) for E2E testing where your UI Plugin must be uploaded to live Cloud Director Instance and you can perform the E2E testing directly on that Cloud Director Environment.

Steps to perform E2E testing:
- Initialise Cypress project
- Configure it to open given Cloud Director URL in the Cypress browser
- Write your E2E tests in Cypress
- Make sure the UI Plugin that you test is available in the Cloud Director Instance that you configured for E2E testing.

**Comment by swathishetty** [comment]
@nvladimirovi Thanks for the inputs, we did try adding the systemJs and tried setting the registry. The above error was resolved, but there is a new exception thrown now. We did try setting multiple registry, but that did not work. Is there anything which we are missing ?

tried setting below config in systemjs.js

    SystemJS.registry.set('@vcd/sdk', SystemJS.newModule({}));
    SystemJS.registry.set('@vcd-ui/common', SystemJS.newModule({}));
    window['SystemJs'] = SystemJS;

![image](https://github.com/vmware/cloud-director-extension-standard-library/assets/1817776/b459891f-24da-4042-84a2-75c56e3629f1)

**Comment by nvladimirovi** [comment]
@swathishetty I don't think you need to do this
```javascript
SystemJS.registry.set('@vcd/sdk', SystemJS.newModule({}));
```
@vcd/sdk is included in your plugin bundle.js

You need to make sure the code snipped your provided
```javascript
SystemJS.registry.set('@vcd-ui/common', SystemJS.newModule({}));
window['SystemJs'] = SystemJS;
```
is loaded in the browser started by Karma before the tests run.
Can you open the Karma browser and try to see what is in `window.System.registry`? We expect @vcd/common to be listed there.

**Comment by nvladimirovi** [comment]
How do you run Unit Tests, do you load only the bundle.js of your plugin in karma browser or it's another application, what exactly is your project structure?

**Comment by Yogaraju** [comment]
Hi @nvladimirovi,
The folder structure is like below
`|--node_modules
|--src
   |--index.html
   |--systemjs.js
   |--test.ts
|--angular.json
|--karma.conf.js
|--package.json
|--tsconfig.json`

Content inside the files are 
**index.html**
`<!DOCTYPE html>
<html>
    <head> </head>
    <body>
        <script type="text/javascript" src="./systemjs.js"></script>
    </body>
</html>`

**systemjs.js**
`import System from 'systemjs/dist/system'
window.SystemJs = System.registry.set('@vcd-ui/common', System.newModule({}))`

**test.ts**
`import { getTestBed } from '@angular/core/testing'
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing'
 
// Initialize the Angular testing environment.
getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting(), {
    errorOnUnknownElements: true,
    errorOnUnknownProperties: true
})`

**angular.json**
`"test": {
       "builder": "@angular-devkit/build-angular:karma",
       "options": {
               "polyfills": ["zone.js", "zone.js/testing"],
               "tsConfig": "./tsconfig.spec.json"
        }
    }`

**karma.conf.js**
`module.exports = function (config) {
    config.set({
        basePath: '',
        frameworks: ['jasmine', '@angular-devkit/build-angular'],
        plugins: [
            require('karma-jasmine'),
            require('karma-chrome-launcher'),
            require('karma-jasmine-html-reporter'),
            require('karma-coverage'),
            require('@angular-devkit/build-angular/plugins/karma')
        ],
        files: [{ pattern: 'node_modules/systemjs/dist/system.js', included: true, watched: true }],
        client: {
            captureConsole: true,
            jasmine: {
                // you can add configuration options for Jasmine here
                // the possible options are listed at https://jasmine.github.io/api/edge/Configuration.html
                // for example, you can disable the random execution with `random: false`
                // or set a specific seed with `seed: 4321`
            },
            clearContext: false // leave Jasmine Spec Runner output visible in browser
        },
        jasmineHtmlReporter: {
            suppressAll: true // removes the duplicated traces
        },
        coverageReporter: {
            dir: require('path').join(__dirname, './coverage/app-vcloud-plugin'),
            subdir: '.',
            reporters: [{ type: 'html' }, { type: 'text-summary' }]
        },
        reporters: ['progress', 'kjhtml'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['CustomChromeHeadless'],
        customLaunchers: {
            CustomChromeHeadless: {
                base: 'ChromeHeadless',
                flags: [
                    '--no-sandbox',
                    '--disable-web-security',
                    '--js-flags="--max_old_space_size=8192"',
                    '--remote-debugging-port=40707'
                ]
            },
            // Set 'browsers' above to this value in order to have a browser open to view testing
            CustomChrome: {
                base: 'Chrome',
                flags: [
                    '--no-sandbox',
                    '--disable-web-security',
                    '--js-flags="--max_old_space_size=8192"',
                    '--remote-debugging-port=40707'
                ]
            }
        },
        singleRun: false,
        restartOnFileChange: true
    })
}`

**package.json**
`"dependencies": {
        "@angular/animations": "15.2.0",
        "@angular/common": "15.2.0",
        "@angular/compiler": "15.2.0",
        "@angular/core": "15.2.0",
        "@angular/forms": "15.2.0",
        "@angular/platform-browser": "15.2.0",
        "@angular/platform-browser-dynamic": "15.2.0",
        "@angular/router": "15.2.0",
        "@cds/core": "6.3.1",
        "@clr/angular": "15.0.3",
        "@clr/ui": "15.0.3",
        "@ngrx/store": "10.1.2",
        "@vcd/bindings": "9.1.1",
        "@vcd/i18n": "12.0.0",
        "@vcd/plugin-builders": "15.0.1",
        "@vcd/sdk": "15.0.2",
        "clone-deep": "^4.0.1",
        "rxjs": "7.8.0",
        "tslib": "2.3.0",
        "zone.js": "0.12.0"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^15.2.10",
        "@angular/cli": "15.2.3",
        "@types/clone-deep": "^4.0.4",
        "@types/jasmine": "~4.3.0",
        "@types/jest": "^29.5.9",
        "@types/node": "^18.18.0",
        "@types/systemjs": "^6.13.5",
        "jasmine-core": "~4.6.0",
        "karma": "~6.4.0",
        "karma-chrome-launcher": "~3.2.0",
        "karma-coverage": "~2.2.0",
        "karma-jasmine": "~5.1.0",
        "karma-jasmine-html-reporter": "~2.1.0",
        "systemjs": "0.20.19",
        "typescript": "4.9.4"
    }`

We tried to set only `@vcd-ui/common` and print the `window.System.registry` but we couldn't find @vcd/common
![image](https://github.com/vmware/cloud-director-extension-standard-library/assets/31246754/b2767ab3-2066-4bee-9b2b-c8a66bdb0543)

**Comment by Yogaraju** [comment]
Hi @nvladimirovi, replying to questions for @swathishetty
Our folder structure is like below

- node_modules
- src
   -index.html
   -systemjs.js
   -test.ts
- angular.json
- karma.conf.js
- package.json`

Content inside the files are
**index.html**
```
<!DOCTYPE html>
<html>
    <head> </head>
    <body>
        <script type="text/javascript" src="./systemjs.js"></script>
    </body>
</html>
```
**systemjs.js**
```
import System from 'systemjs/dist/system'
window.SystemJs = System.registry.set('@vcd-ui/common', System.newModule({}))
```

**test.ts**
```
import { getTestBed } from '@angular/core/testing'
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing'

// Initialize the Angular testing environment.
getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting(), {
errorOnUnknownElements: true,
errorOnUnknownProperties: true
})
```

**angular.json**
```
"test": {
      "builder": "@angular-devkit/build-angular:karma",
      "options": {
              "polyfills": ["zone.js", "zone.js/testing"],
              "tsConfig": "./tsconfig.spec.json",
              "scripts": ["node_modules/systemjs/dist/system.js"]
        }
}
```

**karma.conf.js**
```
module.exports = function (config) {
    config.set({
        basePath: '',
        frameworks: ['jasmine', '@angular-devkit/build-angular'],
        plugins: [
            require('karma-jasmine'),
            require('karma-chrome-launcher'),
            require('karma-jasmine-html-reporter'),
            require('karma-coverage'),
            require('@angular-devkit/build-angular/plugins/karma')
        ],
        files: [{ pattern: 'node_modules/systemjs/dist/system.js', included: true, watched: true }],
        client: {
            captureConsole: false,
            jasmine: {
                // you can add configuration options for Jasmine here
                // the possible options are listed at https://jasmine.github.io/api/edge/Configuration.html
                // for example, you can disable the random execution with `random: false`
                // or set a specific seed with `seed: 4321`
            },
            clearContext: false // leave Jasmine Spec Runner output visible in browser
        },
        jasmineHtmlReporter: {
            suppressAll: true // removes the duplicated traces
        },
        coverageReporter: {
            dir: require('path').join(__dirname, './coverage/app-vcloud-plugin'),
            subdir: '.',
            reporters: [{ type: 'html' }, { type: 'text-summary' }]
        },
        reporters: ['progress', 'kjhtml'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_DEBUG,
        autoWatch: true,
        browsers: ['Chrome'],
        customLaunchers: {
            CustomChromeHeadless: {
                base: 'ChromeHeadless',
                flags: [
                    '--no-sandbox',
                    '--disable-web-security',
                    '--js-flags="--max_old_space_size=8192"',
                    '--remote-debugging-port=40707'
                ]
            }
            // Set 'browsers' above to this value in order to have a browser open to view testing
            // CustomChrome: {
            //     base: 'Chrome',
            //     flags: [
            //         '--no-sandbox',
            //         '--disable-web-security',
            //         '--js-flags="--max_old_space_size=8192"',
            //         '--remote-debugging-port=40707'
            //     ]
            // }
        },
        singleRun: false,
        restartOnFileChange: false
    })
}
```

**package.json**
```
"dependencies": {
        "@angular/animations": "15.2.0",
        "@angular/common": "15.2.0",
        "@angular/compiler": "15.2.0",
        "@angular/core": "15.2.0",
        "@angular/forms": "15.2.0",
        "@angular/platform-browser": "15.2.0",
        "@angular/platform-browser-dynamic": "15.2.0",
        "@angular/router": "15.2.0",
        "@cds/core": "6.3.1",
        "@clr/angular": "15.0.3",
        "@clr/ui": "15.0.3",
        "@ngrx/store": "10.1.2",
        "@vcd/bindings": "9.1.1",
        "@vcd/i18n": "12.0.0",
        "@vcd/plugin-builders": "15.0.1",
        "@vcd/sdk": "15.0.2",
        "clone-deep": "^4.0.1",
        "rxjs": "7.8.0",
        "tslib": "2.3.0",
        "zone.js": "0.12.0"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^15.2.10",
        "@angular/cli": "15.2.3",
        "@types/clone-deep": "^4.0.4",
        "@types/jasmine": "~4.3.0",
        "@types/jest": "^29.5.9",
        "@types/node": "^18.18.0",
        "@types/systemjs": "^6.13.5",
        "jasmine-core": "~4.6.0",
        "karma": "~6.4.0",
        "karma-chrome-launcher": "~3.2.0",
        "karma-coverage": "~2.2.0",
        "karma-jasmine": "~5.1.0",
        "karma-jasmine-html-reporter": "~2.1.0",
        "systemjs": "0.20.19",
        "typescript": "4.9.4"
    }
```

We tried to set only `@vcd-ui/common` as you suggested and print `window.System.registry` but we couldn't find @vcd/common
![image](https://github.com/vmware/cloud-director-extension-standard-library/assets/31246754/ca82b32e-6908-4eae-a6a6-474d90853528)

**Comment by nvladimirovi** [comment]
@Yogaraju can you try to add `systemjs.js` file you create as polyfill in `angular.json`.
```json
"test": {
      "builder": "@angular-devkit/build-angular:karma",
      "options": {
              "polyfills": ["zone.js", "zone.js/testing", "./src/systemjs.js"],
              "tsConfig": "./tsconfig.spec.json",
              "scripts": ["node_modules/systemjs/dist/system.js"]
        }
}
```
or as a script
```json
"test": {
      "builder": "@angular-devkit/build-angular:karma",
      "options": {
              "polyfills": ["zone.js", "zone.js/testing"],
              "tsConfig": "./tsconfig.spec.json",
              "scripts": ["node_modules/systemjs/dist/system.js", "./src/systemjs.js"]
        }
}
```
I don't think Karma is using the index.html file you created.

**Comment by Yogaraju** [comment]
Hi @nvladimirovi, I tried adding `systemjs.js` inside polyfills and it worked. I can now see `window.System.registry` setting @vcd/common and @vcd-ui/common but still the error resides.

![image](https://github.com/vmware/cloud-director-extension-standard-library/assets/31246754/e46c3285-6955-4d44-8e85-d91ac2117d4a)

**Comment by nvladimirovi** [comment]
@Yogaraju can you run karam in debug and place a breakpoint in the file where the exception occurs, from the screenshot looks like the exception is thrown in `vcd-sdk.mjs:574:11`. Search for `let containerHooks = window.System.registry.get('@vcd/common');` and place a breakpoint to inspect the value of `containerHooks`.

**Comment by Yogaraju** [comment]
Hi @nvladimirovi, I put debugger in `vcd-sdk.mjs` file. It seems like `window.System.registry` does not have @vcd/common and @vcd-ui/common modules, hence, `containerHooks` will be undefined.

![image](https://github.com/vmware/cloud-director-extension-standard-library/assets/31246754/388ee128-3cda-44c9-9171-0056d85dfc26)

**Comment by nvladimirovi** [comment]
Okay, here is how you can run unit tests for now, with one drawback, some extensibility features that you import from @vcd/sdk may not work.
We would need some time to add support for karma as testing framework.

In the below steps the assumption is made that your tests are in `packages/uiPlugin/src/main`.

# Step 1
In `./packages/uiPlugin/package.json` make sure you installed these dependencies
```json
{
    "devDependencies": {
        "@angular/cli": "15.2.3",
        "@types/jasmine": "~4.3.0",
        "jasmine-core": "~4.5.0",
        "karma": "~6.4.0",
        "karma-chrome-launcher": "~3.1.0",
        "karma-coverage": "~2.2.0",
        "karma-jasmine": "~5.1.0",
        "karma-jasmine-html-reporter": "~2.0.0",
        "systemjs": "0.20.19",
        "typescript": "4.9.4"
      }
}
```
# Step 2
In `./packages/uiPlugin/package.json` add
```json
{
    "scripts": {
        "test": "ng test"
     },
}
```

# Step 3
In `./packages/uiPlugin/angular.json` add this configuration for testing
```json
{
    "test": {
      "builder": "@angular-devkit/build-angular:karma",
      "options": {
        "polyfills": [
          "zone.js",
          "zone.js/testing"
        ],
        "tsConfig": "tsconfig.spec.json",
        "inlineStyleLanguage": "scss",
        "assets": [
          "src/favicon.ico",
          "src/assets"
        ],
        "styles": [
          "src/styles.scss"
        ],
        "scripts": [
          "./node_modules/systemjs/dist/system.js",
          "./systemjs.js"
        ]
      }
    }
}
```

# Step 4
Create `./packages/uiPlugin/tsconfig.spec.json` with this configuration
```
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
      "outDir": "./out-tsc/spec",
      "types": [
        "jasmine"
      ]
    },
    "include": [
      "src/**/*.spec.ts",
      "src/**/*.d.ts",
    ]
}
```
# Step 5
Create `packages/uiPlugin/systemjs.js` with the following code
```javascript
window.System.registry.set("@vcd/common", System.newModule({}));
```
# Step 6
In your unit test config make sure you set the following
```typescript
describe('MyComponent', () => {
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [
        RouterTestingModule,
        ClarityModule, <--- Clarity Support
        I18nModule.forChild(),  <--- Localization Support
      ],
      declarations: [
        MyComponent
      ],
    }).compileComponents();
  });
});
```

You should be able to run the Karma unit tests after these steps.

**Comment by nvladimirovi** [comment]
@Yogaraju I added the support for Karma and Cypress (as E2E testing framework) in that PR, check it if you need e2e testing. https://github.com/vmware/cloud-director-extension-standard-library/pull/31

**Comment by nvladimirovi** [comment]
@Yogaraju in `systemjs.js` add the following code
```javascript
class EntityActionExtensionComponent {}
class WizardExtensionComponent {}
class WizardExtensionWithValidationComponent {}
class WizardExtensionWithContextComponent {}

window["System"].registry.set("@vcd/common", window["System"].newModule({
    EntityActionExtensionComponent,
    WizardExtensionComponent,
    WizardExtensionWithValidationComponent,
    WizardExtensionWithContextComponent,
    API_ROOT_URL: "API_ROOT_URL",
    FLEX_APP_URL: "FLEX_APP_URL",
    SESSION_SCOPE: "SESSION_SCOPE",
    SESSION_ORGANIZATION: "SESSION_ORGANIZATION",
    EXTENSION_ASSET_URL: "EXTENSION_ASSET_URL",
    EXTENSION_ROUTE: "EXTENSION_ROUTE",
    SDK_MODE: "SDK_MODE",
    SESSION_ORG_ID: "SESSION_ORG_ID",
}));
```

For the `@InjectionTokens` from the above list, if you use for example `API_ROOT_URL` then you need to provide it in the unit test module as below.
```
await TestBed.configureTestingModule({
  imports: [
    RouterTestingModule,
    ClarityModule,
    I18nModule.forChild(),
  ],
  declarations: [
    ApplicationComponent
  ],
  providers: [
    {provide: "API_ROOT_URL", useValue: "https://localhost" },
  ]
}).compileComponents();
```

**Comment by swathishetty** [comment]
@nvladimirovi  We were able to run our test bed. Appreciate your quick assistance. Thank you.
